# This file is the entry point to configure your own services.
# Files in the packages/ subdirectory configure your dependencies.

# Put parameters here that don't need to change on each machine where the app is deployed
# https://symfony.com/doc/current/best_practices.html#use-parameters-for-application-configuration
parameters:

services:
    # default configuration for services in *this* file
    _defaults:
        autowire: true      # Automatically injects dependencies in your services.
        autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.

    # makes classes in src/ available to be used as services
    # this creates a service per class whose id is the fully-qualified class name
    App\:
        resource: '../src/'

    # add more service definitions when explicit configuration is needed
    # please note that last definitions always *replace* previous ones

    # Security services
    App\Security\RedmineUserProvider:
        arguments:
            $userRepository: '@App\Repository\UserRepository'

    App\Security\Service\PermissionService:
        arguments:
            $entityManager: '@doctrine.orm.entity_manager'
            $memberRepository: '@App\Repository\MemberRepository'
            $roleRepository: '@App\Repository\RoleRepository'

    # Security voters
    App\Security\Voter\ProjectVoter:
        arguments:
            $permissionService: '@App\Security\Service\PermissionService'
        tags:
            - { name: security.voter }

    App\Security\Voter\IssueVoter:
        arguments:
            $permissionService: '@App\Security\Service\PermissionService'
        tags:
            - { name: security.voter }

    App\Security\Voter\TimeEntryVoter:
        arguments:
            $permissionService: '@App\Security\Service\PermissionService'
        tags:
            - { name: security.voter }

    App\Security\Voter\WikiVoter:
        arguments:
            $permissionService: '@App\Security\Service\PermissionService'
        tags:
            - { name: security.voter }

    App\Security\Voter\GlobalVoter:
        arguments:
            $permissionService: '@App\Security\Service\PermissionService'
        tags:
            - { name: security.voter }

    # Twig extension
    App\Twig\SecurityExtension:
        arguments:
            $security: '@security.helper'
            $permissionService: '@App\Security\Service\PermissionService'
        tags:
            - { name: twig.extension }
